---
swagger: "2.0"
info:
  title: "Calculator"
  description: ""
  x-ibm-name: "calculator"
  version: "1.0.0"
schemes:
- "https"
basePath: "/Calculator"
produces:
- "application/xml"
consumes:
- "text/xml"
securityDefinitions: {}
x-ibm-configuration:
  type: "wsdl"
  phase: "realized"
  enforced: true
  testable: true
  gateway: "datapower-gateway"
  cors:
    enabled: true
  wsdl-definition:
    wsdl: "http://www.dneonline.com/calculator.asmx?wsdl"
    service: "Calculator"
    port: "CalculatorSoap"
    soap-version: "1.1"
  assembly:
    execute:
    - proxy:
        title: "proxy"
        target-url: "http://www.dneonline.com/calculator.asmx"
paths:
  /Add:
    post:
      summary: "Operation Add"
      description: "Adds two integers. This is a test WebService. ©DNE Online"
      operationId: "Add"
      x-ibm-soap:
        soap-action: "http://tempuri.org/Add"
        soap-operation: "{http://tempuri.org/}Add"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/AddInput"
      responses:
        default:
          description: ""
          schema:
            $ref: "#/definitions/AddOutput"
  /Subtract:
    post:
      summary: "Operation Subtract"
      description: ""
      operationId: "Subtract"
      x-ibm-soap:
        soap-action: "http://tempuri.org/Subtract"
        soap-operation: "{http://tempuri.org/}Subtract"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SubtractInput"
      responses:
        default:
          description: ""
          schema:
            $ref: "#/definitions/SubtractOutput"
  /Multiply:
    post:
      summary: "Operation Multiply"
      description: ""
      operationId: "Multiply"
      x-ibm-soap:
        soap-action: "http://tempuri.org/Multiply"
        soap-operation: "{http://tempuri.org/}Multiply"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/MultiplyInput"
      responses:
        default:
          description: ""
          schema:
            $ref: "#/definitions/MultiplyOutput"
  /Divide:
    post:
      summary: "Operation Divide"
      description: ""
      operationId: "Divide"
      x-ibm-soap:
        soap-action: "http://tempuri.org/Divide"
        soap-operation: "{http://tempuri.org/}Divide"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/DivideInput"
      responses:
        default:
          description: ""
          schema:
            $ref: "#/definitions/DivideOutput"
definitions:
  Security:
    xml:
      namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
      prefix: "wsse"
    description: "Header for WS-Security"
    type: "object"
    properties:
      UsernameToken:
        xml:
          namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
          prefix: "wsse"
        type: "object"
        properties:
          Username:
            xml:
              namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
              prefix: "wsse"
            type: "string"
          Password:
            xml:
              namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
              prefix: "wsse"
            type: "string"
          Nonce:
            xml:
              namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
              prefix: "wsse"
            type: "string"
            properties:
              EncodingType:
                xml:
                  namespace: ""
                  attribute: true
                type: "string"
          Created:
            xml:
              namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
              prefix: "wsu"
            type: "string"
      Timestamp:
        xml:
          namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
          prefix: "wsu"
        type: "object"
        properties:
          Created:
            xml:
              namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
              prefix: "wsu"
            type: "string"
          Expires:
            xml:
              namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
              prefix: "wsu"
            type: "string"
          Id:
            xml:
              namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
              prefix: "wsu"
              attribute: true
            type: "string"
  AddInput:
    type: "object"
    properties:
      Envelope:
        xml:
          prefix: "soapenv"
          namespace: "http://schemas.xmlsoap.org/soap/envelope/"
        type: "object"
        properties:
          Header:
            $ref: "#/definitions/AddHeader"
          Body:
            type: "object"
            properties:
              Add:
                $ref: "#/definitions/Add_tns"
            required:
            - "Add"
        required:
        - "Body"
    required:
    - "Envelope"
    example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
      >\n <soapenv:Header>\n  <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\
      \ xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\"\
      >\n   <wsse:UsernameToken>\n    <wsse:Username>string</wsse:Username>\n    <wsse:Password>string</wsse:Password>\n\
      \    <wsse:Nonce EncodingType=\"string\">string</wsse:Nonce>\n    <wsu:Created>string</wsu:Created>\n\
      \   </wsse:UsernameToken>\n   <wsu:Timestamp wsu:Id=\"string\">\n    <wsu:Created>string</wsu:Created>\n\
      \    <wsu:Expires>string</wsu:Expires>\n   </wsu:Timestamp>\n  </wsse:Security>\n\
      \ </soapenv:Header>\n <soapenv:Body>\n  <tns:Add xmlns:tns=\"http://tempuri.org/\"\
      ><!-- mandatory -->\n   <tns:intA><!-- mandatory -->3</tns:intA>\n   <tns:intB><!--\
      \ mandatory -->3</tns:intB>\n  </tns:Add>\n </soapenv:Body>\n</soapenv:Envelope>"
  AddHeader:
    type: "object"
    properties:
      Security:
        $ref: "#/definitions/Security"
  AddOutput:
    type: "object"
    properties:
      Envelope:
        xml:
          prefix: "soapenv"
          namespace: "http://schemas.xmlsoap.org/soap/envelope/"
        type: "object"
        properties:
          Body:
            type: "object"
            properties:
              AddResponse:
                $ref: "#/definitions/AddResponse_tns"
        required:
        - "Body"
    required:
    - "Envelope"
    example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
      >\n <soapenv:Body>\n  <tns:AddResponse xmlns:tns=\"http://tempuri.org/\">\n\
      \   <tns:AddResult><!-- mandatory -->3</tns:AddResult>\n  </tns:AddResponse>\n\
      \ </soapenv:Body>\n</soapenv:Envelope>"
  SubtractInput:
    type: "object"
    properties:
      Envelope:
        xml:
          prefix: "soapenv"
          namespace: "http://schemas.xmlsoap.org/soap/envelope/"
        type: "object"
        properties:
          Header:
            $ref: "#/definitions/SubtractHeader"
          Body:
            type: "object"
            properties:
              Subtract:
                $ref: "#/definitions/Subtract_tns"
            required:
            - "Subtract"
        required:
        - "Body"
    required:
    - "Envelope"
    example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
      >\n <soapenv:Header>\n  <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\
      \ xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\"\
      >\n   <wsse:UsernameToken>\n    <wsse:Username>string</wsse:Username>\n    <wsse:Password>string</wsse:Password>\n\
      \    <wsse:Nonce EncodingType=\"string\">string</wsse:Nonce>\n    <wsu:Created>string</wsu:Created>\n\
      \   </wsse:UsernameToken>\n   <wsu:Timestamp wsu:Id=\"string\">\n    <wsu:Created>string</wsu:Created>\n\
      \    <wsu:Expires>string</wsu:Expires>\n   </wsu:Timestamp>\n  </wsse:Security>\n\
      \ </soapenv:Header>\n <soapenv:Body>\n  <tns:Subtract xmlns:tns=\"http://tempuri.org/\"\
      ><!-- mandatory -->\n   <tns:intA><!-- mandatory -->3</tns:intA>\n   <tns:intB><!--\
      \ mandatory -->3</tns:intB>\n  </tns:Subtract>\n </soapenv:Body>\n</soapenv:Envelope>"
  SubtractHeader:
    type: "object"
    properties:
      Security:
        $ref: "#/definitions/Security"
  SubtractOutput:
    type: "object"
    properties:
      Envelope:
        xml:
          prefix: "soapenv"
          namespace: "http://schemas.xmlsoap.org/soap/envelope/"
        type: "object"
        properties:
          Body:
            type: "object"
            properties:
              SubtractResponse:
                $ref: "#/definitions/SubtractResponse_tns"
        required:
        - "Body"
    required:
    - "Envelope"
    example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
      >\n <soapenv:Body>\n  <tns:SubtractResponse xmlns:tns=\"http://tempuri.org/\"\
      >\n   <tns:SubtractResult><!-- mandatory -->3</tns:SubtractResult>\n  </tns:SubtractResponse>\n\
      \ </soapenv:Body>\n</soapenv:Envelope>"
  MultiplyInput:
    type: "object"
    properties:
      Envelope:
        xml:
          prefix: "soapenv"
          namespace: "http://schemas.xmlsoap.org/soap/envelope/"
        type: "object"
        properties:
          Header:
            $ref: "#/definitions/MultiplyHeader"
          Body:
            type: "object"
            properties:
              Multiply:
                $ref: "#/definitions/Multiply_tns"
            required:
            - "Multiply"
        required:
        - "Body"
    required:
    - "Envelope"
    example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
      >\n <soapenv:Header>\n  <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\
      \ xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\"\
      >\n   <wsse:UsernameToken>\n    <wsse:Username>string</wsse:Username>\n    <wsse:Password>string</wsse:Password>\n\
      \    <wsse:Nonce EncodingType=\"string\">string</wsse:Nonce>\n    <wsu:Created>string</wsu:Created>\n\
      \   </wsse:UsernameToken>\n   <wsu:Timestamp wsu:Id=\"string\">\n    <wsu:Created>string</wsu:Created>\n\
      \    <wsu:Expires>string</wsu:Expires>\n   </wsu:Timestamp>\n  </wsse:Security>\n\
      \ </soapenv:Header>\n <soapenv:Body>\n  <tns:Multiply xmlns:tns=\"http://tempuri.org/\"\
      ><!-- mandatory -->\n   <tns:intA><!-- mandatory -->3</tns:intA>\n   <tns:intB><!--\
      \ mandatory -->3</tns:intB>\n  </tns:Multiply>\n </soapenv:Body>\n</soapenv:Envelope>"
  MultiplyHeader:
    type: "object"
    properties:
      Security:
        $ref: "#/definitions/Security"
  MultiplyOutput:
    type: "object"
    properties:
      Envelope:
        xml:
          prefix: "soapenv"
          namespace: "http://schemas.xmlsoap.org/soap/envelope/"
        type: "object"
        properties:
          Body:
            type: "object"
            properties:
              MultiplyResponse:
                $ref: "#/definitions/MultiplyResponse_tns"
        required:
        - "Body"
    required:
    - "Envelope"
    example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
      >\n <soapenv:Body>\n  <tns:MultiplyResponse xmlns:tns=\"http://tempuri.org/\"\
      >\n   <tns:MultiplyResult><!-- mandatory -->3</tns:MultiplyResult>\n  </tns:MultiplyResponse>\n\
      \ </soapenv:Body>\n</soapenv:Envelope>"
  DivideInput:
    type: "object"
    properties:
      Envelope:
        xml:
          prefix: "soapenv"
          namespace: "http://schemas.xmlsoap.org/soap/envelope/"
        type: "object"
        properties:
          Header:
            $ref: "#/definitions/DivideHeader"
          Body:
            type: "object"
            properties:
              Divide:
                $ref: "#/definitions/Divide_tns"
            required:
            - "Divide"
        required:
        - "Body"
    required:
    - "Envelope"
    example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
      >\n <soapenv:Header>\n  <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\
      \ xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\"\
      >\n   <wsse:UsernameToken>\n    <wsse:Username>string</wsse:Username>\n    <wsse:Password>string</wsse:Password>\n\
      \    <wsse:Nonce EncodingType=\"string\">string</wsse:Nonce>\n    <wsu:Created>string</wsu:Created>\n\
      \   </wsse:UsernameToken>\n   <wsu:Timestamp wsu:Id=\"string\">\n    <wsu:Created>string</wsu:Created>\n\
      \    <wsu:Expires>string</wsu:Expires>\n   </wsu:Timestamp>\n  </wsse:Security>\n\
      \ </soapenv:Header>\n <soapenv:Body>\n  <tns:Divide xmlns:tns=\"http://tempuri.org/\"\
      ><!-- mandatory -->\n   <tns:intA><!-- mandatory -->3</tns:intA>\n   <tns:intB><!--\
      \ mandatory -->3</tns:intB>\n  </tns:Divide>\n </soapenv:Body>\n</soapenv:Envelope>"
  DivideHeader:
    type: "object"
    properties:
      Security:
        $ref: "#/definitions/Security"
  DivideOutput:
    type: "object"
    properties:
      Envelope:
        xml:
          prefix: "soapenv"
          namespace: "http://schemas.xmlsoap.org/soap/envelope/"
        type: "object"
        properties:
          Body:
            type: "object"
            properties:
              DivideResponse:
                $ref: "#/definitions/DivideResponse_tns"
        required:
        - "Body"
    required:
    - "Envelope"
    example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
      >\n <soapenv:Body>\n  <tns:DivideResponse xmlns:tns=\"http://tempuri.org/\"\
      >\n   <tns:DivideResult><!-- mandatory -->3</tns:DivideResult>\n  </tns:DivideResponse>\n\
      \ </soapenv:Body>\n</soapenv:Envelope>"
  Add_tns:
    xml:
      namespace: "http://tempuri.org/"
      prefix: "tns"
    type: "object"
    properties:
      intA:
        type: "integer"
        format: "int32"
      intB:
        type: "integer"
        format: "int32"
    required:
    - "intA"
    - "intB"
    example: "\n<tns:Add xmlns:tns=\"http://tempuri.org/\">\n <tns:intA><!-- mandatory\
      \ -->3</tns:intA>\n <tns:intB><!-- mandatory -->3</tns:intB>\n</tns:Add>"
  AddResponse_tns:
    xml:
      namespace: "http://tempuri.org/"
      prefix: "tns"
    type: "object"
    properties:
      AddResult:
        type: "integer"
        format: "int32"
    required:
    - "AddResult"
    example: "\n<tns:AddResponse xmlns:tns=\"http://tempuri.org/\">\n <tns:AddResult><!--\
      \ mandatory -->3</tns:AddResult>\n</tns:AddResponse>"
  Subtract_tns:
    xml:
      namespace: "http://tempuri.org/"
      prefix: "tns"
    type: "object"
    properties:
      intA:
        type: "integer"
        format: "int32"
      intB:
        type: "integer"
        format: "int32"
    required:
    - "intA"
    - "intB"
    example: "\n<tns:Subtract xmlns:tns=\"http://tempuri.org/\">\n <tns:intA><!--\
      \ mandatory -->3</tns:intA>\n <tns:intB><!-- mandatory -->3</tns:intB>\n</tns:Subtract>"
  SubtractResponse_tns:
    xml:
      namespace: "http://tempuri.org/"
      prefix: "tns"
    type: "object"
    properties:
      SubtractResult:
        type: "integer"
        format: "int32"
    required:
    - "SubtractResult"
    example: "\n<tns:SubtractResponse xmlns:tns=\"http://tempuri.org/\">\n <tns:SubtractResult><!--\
      \ mandatory -->3</tns:SubtractResult>\n</tns:SubtractResponse>"
  Multiply_tns:
    xml:
      namespace: "http://tempuri.org/"
      prefix: "tns"
    type: "object"
    properties:
      intA:
        type: "integer"
        format: "int32"
      intB:
        type: "integer"
        format: "int32"
    required:
    - "intA"
    - "intB"
    example: "\n<tns:Multiply xmlns:tns=\"http://tempuri.org/\">\n <tns:intA><!--\
      \ mandatory -->3</tns:intA>\n <tns:intB><!-- mandatory -->3</tns:intB>\n</tns:Multiply>"
  MultiplyResponse_tns:
    xml:
      namespace: "http://tempuri.org/"
      prefix: "tns"
    type: "object"
    properties:
      MultiplyResult:
        type: "integer"
        format: "int32"
    required:
    - "MultiplyResult"
    example: "\n<tns:MultiplyResponse xmlns:tns=\"http://tempuri.org/\">\n <tns:MultiplyResult><!--\
      \ mandatory -->3</tns:MultiplyResult>\n</tns:MultiplyResponse>"
  Divide_tns:
    xml:
      namespace: "http://tempuri.org/"
      prefix: "tns"
    type: "object"
    properties:
      intA:
        type: "integer"
        format: "int32"
      intB:
        type: "integer"
        format: "int32"
    required:
    - "intA"
    - "intB"
    example: "\n<tns:Divide xmlns:tns=\"http://tempuri.org/\">\n <tns:intA><!-- mandatory\
      \ -->3</tns:intA>\n <tns:intB><!-- mandatory -->3</tns:intB>\n</tns:Divide>"
  DivideResponse_tns:
    xml:
      namespace: "http://tempuri.org/"
      prefix: "tns"
    type: "object"
    properties:
      DivideResult:
        type: "integer"
        format: "int32"
    required:
    - "DivideResult"
    example: "\n<tns:DivideResponse xmlns:tns=\"http://tempuri.org/\">\n <tns:DivideResult><!--\
      \ mandatory -->3</tns:DivideResult>\n</tns:DivideResponse>"
