swagger: '2.0'
info:
  x-ibm-name: shab2
  title: Shab2
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /shab2
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: $(target-url)$(request.path)
paths: {}
definitions: {}
tags: []
